export enum Screens {
  HOME = 'HOME',
  DASHBOARD = 'DASHBOARD',
  PORTFOLIO = 'PORTFOLIO',
  ETF_DETAILS = 'ETF_DETAILS',
  TRANSACTION = 'TRANSACTION',
  GAME = 'GAME',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_LOGIN = 'AUTH_LOGIN',
  ONBOARDING = 'ONBOARDING',
  PROFILE = 'PROFILE',
}
